### DISCUSSION TITLE
Must PropertyMapping always be a list?

### DISCUSSION THREAD

**Discussion by jpc4242** [tliron/go-puccini#59] [Ideas]
Once again, question since I'm not 100% sure if this is an issue (but I'm almost sure)

I'm trying to parse a file with this text:
```yaml
topology_template:
  substitution_mappings:
    node_type: mynode
    properties:
      flavour_id: simple
```
But I get the
`topology_template.substitution_mappings.properties["flavour_id"]: "string" instead of "list"`  error

Initially I thought that the snippet had some error, and I see that the code always waits for a list of 1 or 2 elements (the later one deprectaed in TOSCA 1.3 according to the code comments)

But then I found that the TOSCA 1.2 document itself is using simple values for properties in substituttion mappings (section 14.4.1.2 , page 346
```yaml
substitution_mappings:
   node_type: tosca.samples.nodes.MyAbstractMessagingSystem
   properties:
      scaling: [ scaling_input ]
      highly_available: true <-------------------------- HERE!!!
```

And section 3.8.8 confirms that a single string (constant value) is valid (highlight is mine)
> 3.8.8 Property mapping 
A property mapping allows to map the property of a substituted node type to a property definition or value
(mapped as a constant value property definition) within the topology template. 
A property mapping may refer to an input of the topology, to the property of a node template in the 
topology **or be assigned to a constant value.** 

I also checked and TOSCA 1.3 discontinued this, but for TOSCA <=1.2 it should be supported

Should PropertyMapping, REadPropertyMapping, ....  be modified to accept also a constant value? (for tosca<=1.2)

This is one of those things needed to support ETSI SOL001 2.7.1
