### DISCUSSION TITLE
About QuirkSubstitutionMappingsRequirementsAllowDangling

### DISCUSSION THREAD

**Discussion by jpc4242** [tliron/go-puccini#61] [General]
This is to check if the proposed quirk QuirkSubstitutionMappingsRequirementsAllowDangling in https://github.com/tliron/puccini/pull/58, or it is a bug in puccini (or tosca itself):

When SOL001 wants to expose (externally to a VNF) an internal port, the way it species it must be done is as follows:
```yaml
topology_template:
  substitution_mappings:
    node_type: MyCompany.SunshineDB.1_0.1_0
    requirements:
      virtual_link: [ dbBackendIpv4, virtual_link ] # the virtual_link requirement for the dbBackendIpv4 port
 ...
  node_templates:
    dbBackendIpv4:
      type: tosca.nodes.nfv.VduCp
…
      requirements:
       #- virtual_link: # Commented out, it must be left "unresolved" in the node_template 
        - virtual_binding: dbBackend
```

So, substitution_mappings requirement needs to reference an _unassigned_ requirement of a node in node_templates

But if you try to run these constructs past puccini, you get this error
`@89,38 topology_template.substitution_mappings.requirements["virtual_link"][1]: unknown requirement reference in node template "dbBackendIpv4": virtual_link`

I understand that the reasoning behind this behavior may come from TOSCA sentence:
> “[substitution_mapping] ..defines how requirements of the substituted node (or the requirements defined by the node type
of the substituted node template, respectively) are bound to requirements of node templates defined in the topology template.”

So if the node_template did not declare that requirement then substitution_mapping may not refer to it.

My new quirk simply stops puccini from complaining when this situation is found.
But now that yo mention it, it _might_ be a bug in puccini and no quirk would be needed. Otherwise, how would a requirement mapping work?

If there is a different "TOSCA approved" way to do this, then we need to keep the quirk because SOL001 specifies that it must be done the way I describe above. But if SOL001 way is correct, then puccini has to be modified (and we don't need the new quirk)
